{
  "timestamp": "2025-04-07T17:24:03.764369",
  "error_type": "Exception",
  "error_message": "Database error",
  "traceback": "Traceback (most recent call last):\n  File \"/home/andrii/Documents/Projects/Mathtermind/src/services/course_service.py\", line 220, in filter_courses\n    db_courses = course_repo.get_all_courses(self.db)\n  File \"/usr/lib/python3.13/unittest/mock.py\", line 1167, in __call__\n    return self._mock_call(*args, **kwargs)\n           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/unittest/mock.py\", line 1171, in _mock_call\n    return self._execute_mock_call(*args, **kwargs)\n           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/unittest/mock.py\", line 1226, in _execute_mock_call\n    raise effect\nException: Database error\n",
  "system_info": {
    "platform": "Linux-6.12.19-1-lts-x86_64-with-glibc2.41",
    "python_version": "3.13.2",
    "hostname": "archlinux",
    "pid": 1425626,
    "cwd": "/home/andrii/Documents/Projects/Mathtermind",
    "user": "andrii",
    "executable": "/home/andrii/Documents/Projects/Mathtermind/venv/bin/python"
  },
  "additional_data": {
    "operation": "filter_courses",
    "filters": {
      "difficulty_level": "Beginner"
    }
  }
}